name: auto-report-safe-shangqiuxueyuan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: started
  schedule:
    - cron: 0 2,14 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Checkin
      run: |
        gonghao='${{ secrets.GH }}'
        shoujihao='${{ secrets.SJH }}'
        random_time=$(($RANDOM % 3))
        echo "等待 ${random_time} 分钟后开始签到"
        for((i=1;i<=${random_time};i++));  
        do
        echo "倒计时:剩余 $[${random_time}-$i] 分钟"
        sleep 1m
        done 

        for ((i=0;i<1;i++))
        do
        python3 C189Checkin.py <<EOF
        $gonghao
        $shoujihao
        EOF
        done
